---
- hosts: datagovweb
  tasks:
    - name: install epel
      action: command creates=/etc/yum.repos.d/epel.repo rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-7.noarch.rpm
    - name: make sure packages are installed
      action: yum pkg=$item state=installed
      with_items:
        - atool
        - git
    - name: copy repo
      action: copy src=ckan.repo dest=/etc/yum.repos.d/
