---
- hosts: build
  vars_prompt:
   - name: version
     prompt: "Ckan Version"
     private: False
   - name: iteration
     prompt: "Iteration"
     private: False
  tasks:
    - name: make sure packages are installed
      action: apt pkg=$item state=installed
      with_items:
        - rubygems
        - python-virtualenv
        - python-setuptools
        - git-core
        - python-dev
        - ruby1.8-dev
        - postgresql
        - libpq-dev
        - libxml2-dev
        - libxslt1-dev
        - build-essential
        - bison
        - apache2
        - libapache2-mod-wsgi
        - nginx
    - name: install fpm
      action: command gem install -v 0.4.21 fpm creates=/usr/bin/fpm
    - name: get ckan version
      action: git repo=https://github.com/okfn/ckan dest=/usr/lib/ckan/src/ckan version=release-v${version}
    - name: get pip
      action: easy_install name=pip

    - name: install requirements and make virtualenv
      action: pip requirements=/usr/lib/ckan/src/ckan/pip-requirements.txt virtualenv=/usr/lib/ckan/

    - name: run setup.py develop for ckan
      action: command chdir=/usr/lib/ckan/src/ckan/ ../../bin/python setup.py develop

    - name: create directories
      action: file path=$item state=directory
      with_items:
        - /etc/ckan

    - name: copy all needed files
      action: copy src=$item dest=/$item
      with_items:
        - etc/ckan/who.ini
        - etc/ckan/apache.wsgi
        - etc/ckan/production.ini
        - etc/apache2/conf.d/ckan.conf
        - etc/nginx/conf.d/ckan.conf

    - name: copy executables
      action: copy src=$item dest=/$item mode=744
      with_items:
        - usr/bin/ckan
        - tmp/after_web.sh

    #- name: restart apache
      #action: service name=apache2 state=restarted

    - name: build deb main
      action: command fpm -t deb -s dir --description='CKAN package' --after-install=/tmp/after_web.sh -n ckan-2.0 --iteration $iteration -v $version -d postgresql -d nginx -d apache2 -d libapache2-mod-wsgi --config-files /etc/ckan/production.ini --config-files /etc/apache2/conf.d/ckan.conf /usr/bin/ckan /usr/lib/ckan/ /etc/ckan/ /etc/nginx/conf.d/ckan.conf /etc/cron.daily/remove_old_sessions
