---
- hosts: build
  vars_prompt:
   - name: version
     prompt: "Ckan Version"
     private: False
   - name: iteration
     prompt: "Iteration"
     private: False
  tasks:
    - name: make sure packages are installed
      action: apt pkg={{ item }} state=installed
      with_items:
        - rubygems
        - python-virtualenv
        - python-setuptools
        - git-core
        - python-dev
        - ruby1.8-dev
        - postgresql
        - libpq-dev
        - libxml2-dev
        - libxslt1-dev
        - build-essential
        - apache2
        - libapache2-mod-wsgi
        - nginx

    - name: install fpm
      action: command gem install -v 0.4.21 fpm creates=/usr/local/bin/fpm

    - name: delete old directories
      action: file path={{ item }} state=absent
      with_items:
        - /etc/ckan
        - /usr/lib/ckan

    - name: pull ckan version
      action: git repo=https://github.com/okfn/ckan dest=/usr/lib/ckan/default/src/ckan version=release-v{{ version }}

    - name: get pip
      action: easy_install name=pip

    - name: check requirements file name
      shell: "[ -f /usr/lib/ckan/default/src/ckan/pip-requirements.txt ] && echo 'pip-requirements.txt' || echo 'requirements.txt'"
      register: requirements_file_name

    - name: install requirements and make virtualenv for ckan
      action: pip requirements=/usr/lib/ckan/default/src/ckan/{{ requirements_file_name.stdout }} virtualenv=/usr/lib/ckan/default/ virtualenv_site_packages=no

    - name: run setup.py develop for ckan
      action: command chdir=/usr/lib/ckan/default/src/ckan/ ../../bin/python setup.py develop

    - include: datapusher.yml datapusher=false

    - name: install b2 extension
      action: git repo=https://github.com/ckan/ckanext-b2 dest=/usr/lib/ckan/default/src/ckanext-b2 version=master

    - name: create directories
      action: file path={{ item }} state=directory
      with_items:
        - /etc/ckan/default
        - /var/www/build

    - name: copy all needed files
      action: copy src={{ item }} dest=/{{ item }}
      with_items:
        - etc/ckan/default/who.ini
        - etc/ckan/default/apache.wsgi
        - etc/apache2/sites-available/ckan_default
        - etc/nginx/sites-available/ckan
        - etc/cron.daily/remove_old_sessions

    - name: copy executables
      action: copy src={{ item }} dest=/{{ item }} mode=744
      with_items:
        - usr/bin/ckan

    - name: template the after web script
      action: template src=tmp/after_web.j2 dest=/tmp/after_web.sh mode=744

    - name: build deb main
      action: command chdir=/var/www/build fpm
              -t deb -s dir
              --name tsb-b2
              --description='b2'
              --license='AGPL v3.0'
              --maintainer='CKAN team <ckan-dev@lists.okfn.org>'
              --vendor='Open Knowledge Foundation'
              --url='http://ckan.org'
              --after-install=/tmp/after_web.sh
              --iteration {{ iteration }}
              --version {{ version }}
              --depends nginx --depends apache2 --depends libapache2-mod-wsgi --depends libpq5
              --config-files /etc/apache2/sites-available/ckan_default --config-files /etc/nginx/sites-available/ckan
              /usr/lib/ckan/ /etc/ckan/ /usr/bin/ckan /etc/cron.daily/remove_old_sessions /etc/apache2/sites-available/ckan_default /etc/nginx/sites-available/ckan
