---
- hosts: all
  vars_prompt:
   - name: iteration
     prompt: "Iteration"
     private: True 
  vars:
   datapusher: False
  tasks:
    - name: update APT cache
      apt: update_cache=yes

    - name: make sure packages are installed
      action: apt pkg={{ item }} state=installed
      with_items:
        - rubygems
        - python-virtualenv
        - python-setuptools
        - git-core
        - python-dev
        - ruby1.8-dev
        - postgresql
        - libpq-dev
        - libxml2-dev
        - libxslt1-dev
        - build-essential
        - apache2
        - libapache2-mod-wsgi
        - nginx

    - name: install fpm
      action: command gem install -v 0.4.21 fpm creates=/usr/local/bin/fpm

    - name: delete old directories
      action: file path={{ item }} state=absent
      with_items:
        - /etc/ckan
        - /usr/lib/ckan

    - name: pull ckan version
      action: git repo=https://github.com/okfn/ckan dest=/usr/lib/ckan/default/src/ckan version=datapackager

    - name: get pip
      action: easy_install name=pip

    - name: check requirements file name
      shell: "[ -f /usr/lib/ckan/default/src/ckan/pip-requirements.txt ] && echo 'pip-requirements.txt' || echo 'requirements.txt'"
      register: requirements_file_name

    - name: install requirements and make virtualenv for ckan
      action: pip requirements=/usr/lib/ckan/default/src/ckan/{{ requirements_file_name.stdout }} virtualenv=/usr/lib/ckan/default/ virtualenv_site_packages=no

    - name: run setup.py develop for ckan
      action: command chdir=/usr/lib/ckan/default/src/ckan/ ../../bin/python setup.py develop

    - name: install datapackager extension
      action: git repo=https://github.com/ckan/ckanext-datapackager dest=/usr/lib/ckan/default/src/ckanext-datapackager version=master

    - name: install requirements for datapackager
      action: pip requirements=/usr/lib/ckan/default/src/ckanext-datapackager/requirements.txt virtualenv=/usr/lib/ckan/default

    - name: install downloadsdf extension
      action: git repo=https://github.com/ckan/ckanext-downloadsdf dest=/usr/lib/ckan/default/src/ckanext-downloadsdf version=master

    - name: install requirements for downloadsdf
      action: pip requirements=/usr/lib/ckan/default/src/ckanext-downloadsdf/requirements.txt virtualenv=/usr/lib/ckan/default

    - name: install simplecsvpreview extension
      action: git repo=https://github.com/ckan/ckanext-simplecsvpreview dest=/usr/lib/ckan/default/src/ckanext-simplecsvpreview version=master

#    - name: install requirements for downloadsdf
#      action: pip requirements=/usr/lib/ckan/default/src/ckanext-downloadsdf/requirements.txt virtualenv=/usr/lib/ckan/default
    - name: compile pyc
      action: command /usr/lib/ckan/default/bin/python -m compileall /usr/lib/ckan/default/src

    - name: create directories
      action: file path={{ item }} state=directory
      with_items:
        - /etc/ckan/default
        - /var/www/build

    - name: copy all needed files
      action: copy src={{ item }} dest=/{{ item }}
      with_items:
        - etc/ckan/default/who.ini
        - etc/ckan/default/apache.wsgi
        - etc/apache2/sites-available/ckan_default
        - etc/nginx/sites-available/ckan
        - etc/cron.daily/remove_old_sessions

    - name: copy executables
      action: copy src={{ item }} dest=/{{ item }} mode=744
      with_items:
        - usr/bin/ckan

    - name: template the after web script
      action: template src=tmp/after_web.j2 dest=/tmp/after_web.sh mode=744

    - name: build deb main
      action: command chdir=/vagrant fpm
              -t deb -s dir
              --name datapackager
              --description='datapackager'
              --license='AGPL v3.0'
              --maintainer='CKAN team <ckan-dev@lists.okfn.org>'
              --vendor='Open Knowledge Foundation'
              --url='http://ckan.org'
              --after-install=/tmp/after_web.sh
              --iteration {{ iteration }}
              --version 0.0.4
              --depends nginx --depends apache2 --depends libapache2-mod-wsgi --depends libpq5
              --config-files /etc/apache2/sites-available/ckan_default --config-files /etc/nginx/sites-available/ckan
              /usr/lib/ckan/ /etc/ckan/ /usr/bin/ckan /etc/cron.daily/remove_old_sessions /etc/apache2/sites-available/ckan_default /etc/nginx/sites-available/ckan
